export const ADD_FIRM = "ADD_FIRM"
export const DELETE_FIRM = "DELETE_FIRM"
export const BOOK_LAWYER_SLOTS = "BOOK_LAWYER_SLOTS"
export const FORMAT_DATA = "FORMAT_DATA"
export const ADD_LAWYER = "ADD_LAWYER"
